name: my_env
channels:
  - conda-forge
  - rdkit
dependencies:
  - python=3.10
  - rdkit=2022.09.5
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - streamlit=1.22.0
  - mordred=1.2.0
  - matplotlib=3.7.1
  - numpy=1.23.5